### ISSUE TITLE
"VolumeDriver.Mount: could not mount 

### ISSUE THREAD

**Issue by naimax** [costela/docker-volume-hetzner#3]
Hello! I try to connect the volume to the working node of the swarm. Gives such an error. Help me to understand.

`Shutdown            Rejected less than a second ago    "VolumeDriver.Mount: could not mount '/dev/disk/by-id/scsi-0HC_Volume_3651104' as any of [ext4 xfs ext3 ext2]"`

```
redis-data:
    driver: hetzner
    driver_opts:
      size: '10'
```
