### ISSUE TITLE
"unable to authenticate (unauthorized)" error

### ISSUE THREAD

**Issue by slhck** [costela/docker-volume-hetzner#6]
Trying to set up a new volume:

```
➜ cat docker-compose.yml 
version: "3.5"

volumes:
    test:
        driver: hetzner
        driver_opts:
            apikey: xxxx
            fstype: xfs
            size: 10 # in GB, default: 10
            loglevel: debug
```

When running `docker-compose up`, I get:

```
Creating volume "docker-volume-test_test" with hetzner driver
ERROR: create docker-volume-test_test: VolumeDriver.Create: could not get cloud server 'test': unable to authenticate (unauthorized)
```

Note that the token is correct; I could successfully activate the context in `hcloud` and run:

```
➜ ~/go/bin/hcloud server describe test
ID:     xxxxxxxx
Name:       test
Status:     running
Created:    Wed Dec 11 09:00:43 CET 2019 (5 hours ago)
Server Type:    cx41 (ID: 7)
  ID:       7
  Name:     cx41
  Description:  CX41
  Cores:    4
  Memory:   16 GB
  Disk:     160 GB
  Storage Type: local
Public Net:
  IPv4:
    IP:     xx.xx.xx.xx
    Blocked:    no
    DNS:    static.xx.xx.xx.xx.clients.your-server.de
  IPv6:
    IP:     xx.xx.xx.xx
    Blocked:    no
  Floating IPs:
    No Floating IPs
Private Net:
  - ID:         17489
    Name:       internal-network
    IP:         10.0.0.4
    MAC Address:    86:00:00:39:19:92
    Alias IPs:      -
Volumes:
  No Volumes
Image:
  ID:       168855
  Type:     system
  Status:   available
  Name:     ubuntu-18.04
  Description:  Ubuntu 18.04
  Image size:   -
  Disk size:    5 GB
  Created:  Wed May  2 13:02:30 CEST 2018 (2 years ago)
  OS flavor:    ubuntu
  OS version:   18.04
  Rapid deploy: yes
Datacenter:
  ID:       2
  Name:     nbg1-dc3
  Description:  Nuremberg 1 DC 3
  Location:
    Name:       nbg1
    Description:    Nuremberg DC Park 1
    Country:        DE
    City:       Nuremberg
    Latitude:       49.452102
    Longitude:      11.076665
Traffic:
  Outgoing: 7.4 MB
  Ingoing:  2.4 GB
  Included: 22 TB
Backup Window:  Backups disabled
Rescue System:  disabled
ISO:
  No ISO attached
Protection:
  Delete:   no
  Rebuild:  no
Labels:
  No labels
```

Any idea what's wrong? When I run `hostname`, I also get `test`.
