### ISSUE TITLE
Unable to connect to plugin

### ISSUE THREAD

**Issue by mrkamel** [costela/docker-volume-hetzner#9]
Hi,

thx for the plugin!
I'm trying to use it with docker swarm, but can't get it to work.
I set it up like described in the readme.
This is my exemplatory docker-compose file for the stack:

```yaml
version: '3.7'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql/data

volumes:
  mysql-data:
    driver: hetzner
```

when i deploy my stack using 

```bash
docker stack deploy -c mysql.yml mysql
```

the docker logs show:

```
Unable to connect to plugin: /run/docker/plugins/bf53cfb6af1533728ae02cf7768a851edcf83d725a445852381a35e3dd4de7d4/hetzner.sock/VolumeDriver.Create: Post http://%2Frun%2Fdocker%2Fplugins%2Fbf53cfb6af1533728ae02cf7768a851edcf83d725a445852381a35e3dd4de7d4%2Fhetzner.sock/VolumeDriver.Create: EOF, retrying in 1s
```

and the container doesn't start. Due to the error stating `VolumeDriver.Create` i tried to create the volume myself and use it, but then the logs show:

```
Dec 21 10:10:49 116 dockerd[642]: time="2019-12-21T10:10:49.836744136+01:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bf53cfb6af1533728ae02cf7768a851edcf83d725a445852381a35e3dd4de7d4/hetzner.sock/VolumeDriver.Mount: Post http://%2Frun%2Fdocker%2Fplugins%2Fbf53cfb6af1533728ae02cf7768a851edcf83d725a445852381a35e3dd4de7d4%2Fhetzner.sock/VolumeDriver.Mount: EOF, retrying in 1s"
```

My docker version is `19.03.5`

Thx a lot.
